### PR TITLE
add Oxford_CS800 support

### LINKED ISSUE #26: Oxford CryoStream 800 cooler
add support for the [Oxford CryoStream 800 cooler](https://www.oxcryo.com/product/cryostream-800)

* [x] #28 - get status from specified controller
* [x] #29 - identify source of status values `0xFFFE` and `0xFFFF`
* [x] #30 - support screens
* [x] #31 - backpressure signal
* [x] #32 - CS800 python simulator

### PR DESCRIPTION
**Pull request by prjemian**
add support for the Oxford CryoStream 800 cooler to fix #26

### CODE REVIEW

**Comment by timmmooney** [comment]
Hi Pete,

Most autosave request files are named by deleting ".db" from the database name, and adding "_settings.req"  so that autosaveBuild can include it automatically when the database is loaded.

Tim Mooney (mooney@anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Comment by prjemian** [comment]
I wondered how that worked.  Thanks, @timmmooney !

**Comment by prjemian** [comment]
Ready for review now.  Working at 19-ID-D on a single controller.  I'm OK with either a squash or full history merge.

**Review by kmpeters — CHANGES_REQUESTED** [review]
Pete, you should undo the change to the CONFIG_SITE file setting CHECK_RELEASE to WARN.  Many people rely on release checking to catch configuration problems.  Everything else looks OK to me.

If you'd like to avoid committing changes to the RELEASE file in the future, you can put the definitions that work for you in a RELEASE.local file.  This is mostly a style decision, though.

I would vote for squashing the commits.  I usually prefer to retain the development history, but 46 is a lot for someone to sift through if they happen to be looking for another change that occurred during this period.

**Review by kmpeters — APPROVED** [review]

**Review by keenanlang — APPROVED** [review]

**Comment by prjemian** [comment]
@kmpeters , @keenanlang : Thanks!

**Pull request merged**
