### PR TITLE
Support multiple CS800 controllers on one LAN

### LINKED ISSUE #33: Oxford CS800: multiple controllers
The stream-protocol support works when there is only one CS800 controller on the subnet.  When there are multiple controllers, it is not certain to which controller the support will attach.  It may even receive all of status packets broadcast on the subnet.

Write a sequence program to receive the status broadcasts and filter packets from the desired controller by ID (`SetUpControllerNumber`, parameter 1028).  The simulator has been adjusted so a command-line parameter can set the controller ID of the simulator instance.

With this change, *all* CS800 controllers can be controlled from a single IOC (as [described](https://github.com/epics-modules/asyn/issues/108#issuecomment-615937668) in a feature request to the *asyn* module).  The default would attach to any controller, assuming that only one controller is running on the subnet.  This could be checked using ID broadcast traffic on the UDP port 30303.  Those broadcasts only include IP and MAC address but that could be enough.  Better for the support to require controller ID to be specified and matched.

This work can follow merge of #28 so as not to delay further that PR.

### PR DESCRIPTION
**Pull request by prjemian**
Support multiple CS800 controllers to fix #33

Waiting on https://github.com/epics-modules/asyn/pull/109 to merge here.

### CODE REVIEW

**Comment by prjemian** [comment]
If CI succeeds, this is ready to merge.  Except it needs epics-modules/asyn#109

**Comment by prjemian** [comment]
And the upstream CI [fails](epics-modules/asyn#109) on RTEMS.

**Comment by prjemian** [comment]
asyn feature has been merged: https://github.com/epics-modules/asyn/pull/109

**Comment by prjemian** [comment]
and CI now passes - @keenanlang Can you look at this?  The only deficiency is that Oxford_CS800*.adl screens need to be converted to edl, opi, and bob.  I don't know how to do this.

**Comment by MarkRivers** [comment]
I can do the conversion just by typing "make" in the ip/ipApp/op directory once the PR is merged.

**Review by keenanlang — APPROVED** [review]

**Comment by prjemian** [comment]
Thanks!

**Pull request merged**
